# Generated by Django 2.2.5 on 2020-08-11 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0002_auto_20200811_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversations',
            new_name='Conversation',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
